### ISSUE TITLE
Comment to `dcterms:dateCopyrighted`

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#1]
As of 2017-03-08, ISO 15836-2 adds a Note to [`dcterms:copyrighted`](http://dublincore.org/documents/dcmi-terms/#terms-dateCopyrighted): 

    The author of a work has a copyright to the work as soon as it is created.  
    Date copyrighted can predate the date published.

Unless the UC were to decide otherwise, this would be added as a Comment to
`dcterms:copyrighted` in DCMI Metadata Terms after approval of ISO 15836-2. 

However, Stuart says that most copyright schemes internationally use variations
on the phrase "fixed in a tangible medium of expression" rather than "created", 
which implies the text:

    The author of a work has a copyright to the work as soon as it is fixed in
    a tangible medium of expression.  Date copyrighted can predate the date
    published.

## Update 2018-03-26:

The current ISO draft has been amended.  It now reads:
The draft ISO 15836-2 adds the following usage note to "dateCopyrighted":

    NOTE 1 to entry: The year to include in a copyright notice is the year of
    first publication of the work. First publication is when the work is made
    available to the public without restriction. This includes selling a book
    or leaving free copies of it in a public place or posting content on your
    blog.

    [Source: https://www.copyrightlaws.com/copyright-notice-year/]

**Comment by stuartasutton** [comment]
I'd refine the last sentence even further:

>Date of copyright usually predates a date of publication

Use of "copyrighted" may hint at some necessary action on the part of the creator to secure or signal the existence of copyright. Post-Berne Convention, no notice or registration is necessary to secure copyright; it exists instantly at the moment of fixation. Also, "publication" plays no role in copyright other than serving as evidence of a point in time before which a a work has been fixed and may be required by some counties for formal registration of a copyright or for bringing a legal action for breach.

**Comment by tombaker** [comment]
Discussion moved to issue #17
