### ISSUE TITLE
DCMIType PhysicalObject

### ISSUE THREAD

**Issue by HughP** [dcmi/usage#117]
I am wondering can I get some clarity on the use of DCMIType `PhysicalObject`.

For example, when is the [Rosetta Stone](https://en.wikipedia.org/wiki/Rosetta_Stone) a `PhysicalObject` and when is it `Text`? The more common use case might be when is a cassette tape a `physical object` and when is it `sound`? clearly a basket in a museum is a `PhysicalObject`.

[dct:medium](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/medium) suggests that it should be used to indicate physical carrier. Does this mean that such a record should have `PhysicalObject` ?

Note: I am working from the OAI-PMH framework and looking at record cohesion/record quality.

**Comment by kcoyle** [comment]
IMO: Those are questions for your cataloging or metadata creation rules. DC is silent on how you describe your "things". In library cataloging both aspects are included in the description, but there are rules for which one dominates when encoding the type of "thing". In essence, you get to decide by making rules for your use case.

**Comment by tombaker** [comment]
@kcoyle has formulated a good response and there is no obvious need for further discussion by the Usage Board. Closing the issue.
