### ISSUE TITLE
Comment for dct:accrualPeriodicity

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#12]
See [note_accrualPeriodicity.md](../blob/master/proposals/2018_iso-related/note_accrualPeriodicity.md) - see also Issue #11 

-----------------
Add comment for property [http://purl.org/dc/terms/accrualPeriodicity](http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-accrualPeriodicity):

    Recommended best practice is to use a value from the Dublin Core Collection
    Description Frequency Vocabulary [1].
    
    [1] http://dublincore.org/groups/collections/frequency/

Rationale
* Recommends use of a controlled vocabulary published by DCMI, [Frequency Vocabulary](http://dublincore.org/groups/collections/frequency/)

Note
* In ISO 15836-2, this would be published as "NOTE 1 to entry".
* DCMI "owns" the Internet Archive PURL sub-domains for the [Frequency Vocabulary](http://dublincore.org/groups/collections/frequency/), http://purl.org/cld/terms/ and http://purl.org/cld/frequency/ .

**Comment by makxdekkers** [comment]
I do not understand why DCMI would want to discourage the use of other controlled vocabularies. The DCMI vocabulary does not contain all conceivable frequencies, e.g. twice a day, twice a week and twice a month are missing.

In the European DCAT-AP, the use of http://publications.europa.eu/mdr/resource/authority/frequency/html/frequencies-eng.html is recommended which contains the missing terms. More in general, the DCAT-AP recommends the use of controlled vocabularies published and managed by the Publications Office of the EU for use in the European context. I think this practice should be acceptable. The note could just give an example, but not a recommendation. This is something for an application profile.

**Comment by tombaker** [comment]
@makxdekkers I am happy for this to be an example and agree that it is a matter for an application profile.  As with a number of other change proposals that have been turned into issues, the proposed wording came from the ISO Working Group, not DCMI.  I will re-propose with a different wording.

**Comment by tombaker** [comment]
## This issue was consolidated into Issue #34
