### ISSUE TITLE
Comment for dct:audience

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#14]
See [note_audience.md](../blob/master/proposals/2018_iso-related/note_audience.md)

Add comment for property [http://purl.org/dc/terms/audience](http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-audience):

    This property is best used with a formal or informal
    controlled vocabulary of audience types.
    
Note:
* Range of dct:audience is [dct:AgentClass](http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-AgentClass).
* Would be published in ISO 15836-2 as "NOTE 1 to entry:".

**Comment by tombaker** [comment]
Wondering whether it would be simpler to say just:

    This property is best used with a controlled vocabulary of audience types.

I'm wondering if we need to specify that "controlled vocabulary", in this context, means something like "controlled set of URIs" (and not "controlled set of strings").  If we made a change here, we'd need to scan DCMI Metadata Terms for other places where the point applies.  Alternatively, we could make sure there is enough guidance in the Introduction to ISO 15836-2 to cover such cases.

**Comment by kaiec** [comment]
The wording is different from e.g. "Recommended best practice is to use a value from the Collection Description Accrual Policy Vocabulary". I think this should all be formulated consistently.

**Comment by kcoyle** [comment]
I like providing it as "recommended". I'd say "recommended practice" leaving off best because ... well, "best" just isn't necessary. This makes clear what the property is intended to convey as data.

**Comment by sarahartmann** [comment]
But there isn't a "recommended" value vocab for all the properties e. g. there isn't one for " audience" or is there one I'm not aware of?

Would it be consistent to say:
"This property is intended to be used with a formal or informal controlled vocabulary of audience types."

**Comment by tombaker** [comment]
## PLEASE VOTE THUMBS-UP/DOWN

See [note_audience.md](../blob/master/proposals/2018_iso-related/note_audience.md)

Add comment for property [http://purl.org/dc/terms/audience](http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-audience):

    This property is intended to be used with a formal or informal
    controlled vocabulary of audience types.

**Comment by jneubert** [comment]
Well, "controlled vocabulary" - in particular in combination with "informal" - for me sounds like "strings allowed". The explicit range definition may or may not be recognized by the reader.

What about

``
This property is intended to be used with non-literal values from a formal or informal
vocabulary of audience types.
``

**Comment by tombaker** [comment]
@jneubert Point taken.  Can you suggest a better way to put it?

**Comment by jneubert** [comment]
@tombaker The suggestion is in https://github.com/dcmi/usage/issues/14#issuecomment-396907190. That would take up the wording "non-literal values" as in #27, extending it with a hint to existing vocabularies of non-literal values. I don't think "controlled" adds something here, but I may be wrong.

**Comment by tombaker** [comment]
@jneubert Ah, I missed that distinction.  Yes, I agree that this is a better way to put it.  With apologies to Stefanie (who already upvoted), I will re-start the vote.

**Comment by tombaker** [comment]
## PLEASE VOTE THUMBS-UP/DOWN

See [note_audience.md](../blob/master/proposals/2018_iso-related/note_audience.md)

Add comment for property [http://purl.org/dc/terms/audience](http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-audience):

    This property is intended to be used with non-literal values from a formal
    or informal vocabulary of audience types.

**Comment by kcoyle** [comment]
I don't see how you could have a non-literal vocabulary that is "informal". Can we just say "This property is intended to be used with non-literal values." ?

**Comment by tombaker** [comment]
@kcoyle A folksonomy in SKOS?  But I take your point.

**Comment by aisaac** [comment]
How about 
```
This property is intended to be used with non-literal values from a formal
or informal vocabulary of audience types.
```
?

**Comment by juhahakala** [comment]
ISO draft uses now this version: 

This property is intended to be used with non-literal values from a formal
or informal vocabulary of audience types.

but I would rather have "Recommended practice is to use this property with..."

The draft had a few cases of "recommended best practice" while the usual formulation is "recommended practice". I removed all "bests" from the ISO document.

**Comment by tombaker** [comment]
The comment for dct:audience currently proposed in the ISO draft reads:

    This property is intended to be used with non-literal values from a formal
    or informal vocabulary of audience types.

However, following suggestions from Juha, Karen, and Antoine (and for 
consistency with other comments in DCMIMT), it should perhaps read:

    Best practice is to use this property with non-literal values from a
    vocabulary of audience types.

**Comment by tombaker** [comment]
## APPROVED (11 out of 11 votes)
```
Best practice is to use this property with non-literal values from a
vocabulary of audience types.
```
