### ISSUE TITLE
Comment for subproperties of Date

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#15]
## PLEASE VOTE ON [COMMENT BELOW](../issues/15#issuecomment-400716323)

See [note_available.md](../blob/master/proposals/2018_iso-related/note_available.md) and #16 (Comment for dct:date)

Add comment for [http://purl.org/dc/terms/available](http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-available):

    Follow the practices recommended for the property Date to
    describe dates and date ranges.

Note:
* In ISO 15836-2, this would appear as "NOTE 1 to entry:".

**Comment by kaiec** [comment]
Isn't this already implied by being a subproperty (refinement) of dct:date? If we want to make this more explicit, we could add a sentence like "All recommendations of <superproperty> apply" to all similar cases.

**Comment by kcoyle** [comment]
I think it's good to have the recommendation with the property because people may look just at that property and not follow to other points. So I'd put notes similar to Tom's (not thinking hard about the wording here) on all of the subs.

**Comment by jneubert** [comment]
What about timestamps? I've seen this often (and used it myself) for automatically inserted entries, in particular with dct:modified. Should perhaps be discussed at #16 .

**Comment by kcoyle** [comment]
Why send readers to dct:date? In only a few more characters you can give them the information where they are. I'd repeat the instruction in each.

**Comment by kaiec** [comment]
I wouldn't mind to refer to dct:date as it makes it clearer that all these properties describe in fact dates. And according to the discussion in #16 it will probably not be only a few more characters.

Suggestion: Recommended practice is to describe dates, times and date/time ranges
as recommended for the property Date.

In any case this should IMO only be resolved after we decided in #16 to make sure it is in line with whatever is written there.

**Comment by aisaac** [comment]
Could we add in the comment a small bit that would indicate that Data is a super-property of these properties, this may be the opportunity to do a bit of nice-and-cheap education (or eyebrow raising, depending on our ambition) about semantics in DC.

Something like replacing "the property Date." by "the super-property Date." or "the property Date, of which this property is a specialization"

**Comment by jneubert** [comment]
@tombaker Is there any reason why we used dct:Date - with a captial "D" - in the title of this issue and some other places, or has it just slipped in?

**Comment by jneubert** [comment]
According to [today's telecon](https://github.com/dcmi/usage/blob/master/minutes/2018/2018-06-27.dcub-telecon-agenda.md), I've harmonized wording with the [proposal for dct:date](https://github.com/dcmi/usage/issues/16#issuecomment-400667505), added the mention of subPropertyOf relationship as suggested by @aisaac , and removed http://purl.org/dc/terms/dateCopyrighted from the list of properties to which this comment applies. Additionally, I've added an explicit link to the super-property.

**Comment by tombaker** [comment]
Re: the [most recent vote]( ../issues/15#issuecomment-400716323), I would prefer "subproperty" to "specialization" (which we have never used in this context) or even "refinement" (which we actually continue to use in DC terms documentation) but can live with "specialization".

However, I note that the string `([dct:date](http://purl.org/dc/terms/date))` would not work in the ISO document, which (correct me if I'm wrong) does not have clickable links) or in the RDF representations of DCMI Metadata Terms.  It could work as Markdown source for the DCMI Metadata Terms document, but including it here as part of the approved resolution could complicate the design of a new DC terms documentation generator.  Note that the descriptions of `dct:available`, etc, would point to `dc:date` and `dct:date` (by default using the attribute "Refines:"!), so I do not think it is necessary to seek a way to embed a link in the comment as well.

**Comment by kaiec** [comment]
If "Refines" is kept in dcterms, I would suggest to go with refinement to be consistent.

**Comment by juhahakala** [comment]
ISO standards and other ISO technical specifications are published and can be purchased as printed documents or as PDFs. The PDF version can have clickable links. Since many users will still be dependent on printed versions of ISO documents the URIs should be expressed in links.

**Comment by aisaac** [comment]
I am ok for using 'refinement' if the majority thinks it is better. But **only** if the majority thinks this way ;-)

**Comment by tombaker** [comment]
For subproperties of Date, the current ISO draft includes the comment:

    Note 1 to entry: Recommended practice is to describe date, time, or
    period as recommended for the property Date, of which this property is
    a refinement.

After some discussion, it looks to me like this fairly reflects our rough consensus, unless anyone would like to argue that "refinement" (which is consistent with DCMIMT usage) should be replaced with "subproperty" or "specialization".

Unless there is further discussion or down-votes, I will declare victory on this in August.

**Comment by kcoyle** [comment]
How about just:

Note 1 to entry: Recommended practice is to describe date, time, or
period as recommended for the property Date

The entry for these subproperties already makes the relationship to Date clear.

**Comment by aisaac** [comment]
@kcoyle the relationship is clear to us, but I find a bit of redundancy and extra motivation acceptable. It may help people less familiar with what the 'refines' clause in the entry implies.

**Comment by tombaker** [comment]
## APPROVED

Comment for all subproperties of Date:
```
Note 1 to entry: Recommended practice is to describe date, time, or
period as recommended for the property Date, of which this property is
a refinement.
```
