### ISSUE TITLE
Comment for dct:dateCopyrighted

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#17]
## PLEASE VOTE ON [COMMENT BELOW](#issuecomment-401287232)

See [note_dateCopyrighted.md](../blob/master/proposals/2018_iso-related/note_dateCopyrighted.md)

Add comment for [http://purl.org/dc/terms/dateCopyrighted](http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-dateCopyrighted):
    
    The year to include in a copyright notice is the year of first publication
    of the work. First publication is when the work is made available to the
    public without restriction. This includes selling a book or leaving free
    copies of it in a public place or posting content on your blog. 

    [Source: https://www.copyrightlaws.com/copyright-notice-year/]

Note:
* In ISO 15836-2, this would appear as "NOTE 1 to entry:".

**Comment by tombaker** [comment]
The text from the [copyrightlaws.com website](https://www.copyrightlaws.com/copyright-notice-year/) reads:

> WHICH COPYRIGHT NOTICE YEAR SHOULD YOU USE?
> The general rule is that the year to include in a copyright notice is the year of first publication of the work. First publication is when the work is made available to the public without restriction. This includes selling a book or leaving free copies of it in a public place or posting content on your blog. Publication does not include, for example, circulating copies internally to co-workers.

The website page itself is covered by copyright ("COPYRIGHT © 1998 – 2018 COPYRIGHTLAWS.COM"), raising the question whether it would be proper for DCMI to use the text almost verbatim, even with attribution.

I also wonder to what extent this advice is specific to, say, US law.  Would it make just as much sense if translated into, say, Chinese?

**Comment by tombaker** [comment]
In Issue #1 ,  a previous, now-closed issue on this topic, Stuart wrote:
> I'd refine the last sentence even further:

> Date of copyright usually predates a date of publication

> Use of "copyrighted" may hint at some necessary action on the part of the creator to secure or signal the existence of copyright. Post-Berne Convention, no notice or registration is necessary to secure copyright; it exists instantly at the moment of fixation. Also, "publication" plays no role in copyright other than serving as evidence of a point in time before which a a work has been fixed and may be required by some counties for formal registration of a copyright or for bringing a legal action for breach.

**Comment by kcoyle** [comment]
I disagree that the (c) date "usually" predates publication date. The (c) "act" may predate formal publication, but for those items for which only a year is given for both, they are often the same. Also, for online resources such as blog posts, the two are simultaneous as any fixed resource has automatic (c) under today's law.

**Comment by tombaker** [comment]
@kcoyle @stuartasutton Do you agree that the wording of the ISO proposal is in fact covered by `copyrightlaws.com`'s own copyright, and would using this definition without explicitly putting it into quotes constitute plagiarism?  If so, we would need a counterproposal.  Would either of you want to propose one?  Or do you agree with my sense that guidance on copyright is outside of the scope of DCMI Metadata Terms, especially for a vocabulary that is used across many language areas?

**Comment by jneubert** [comment]
I'd like to keep it short, e.g. "Date of copyright (year of first publication of the work)". However, is that true for all jurisdictions? Or can another edition constitute another copyright date in some cases?

Anyway, we would have to exempt dct:dateCopyrighted from the list in #15 , because we would not want to open the whole range of possible date formats here, but have it restricted to years.

**Comment by stuartasutton** [comment]
Unfortunately, the date of copyright and the date of publication are not necessarily coincident. In the laws of many nations under international treaty, copyright arises when a work is fixed in a tangible medium of expression and no longer when that work is published.

**Comment by jneubert** [comment]
Ouch. We cannot harmonize concepts in different law systems, So we probably cannot say much more than the definition, which currently is:
> Date of copyright.

We could add a comment that the date here should be a year (without linking to the whole set of dct:date options), corresponding to the applicable copyright law.

**Comment by vcharles89** [comment]
@aisaac Is there anything from RightsStatements.org which could help clarifying the definition or giving ideas for a recommendation?

**Comment by aisaac** [comment]
@vcharles89 Nothing that we have in rightsstatements.org so far mentions copyright dates. Arguably we're aiming at lightweight statements there. But still I guess the topic is enough a mine field that we would want to commit as little as possible to any specific interpretation.
As reminded by @jneubert and @stuartasutton , copyright laws depend on jurisdiction and we should not seek to harmonize jurisdictions.

In fact the recommendation is even worse than what I've complained about during the call. For the recommendation comes from a site (https://www.copyrightlaws.com/) that seems dedicated to UK copyright law (they have a different, specific section for US and Canada laws). I think it would be a bad signal to use such a site for an international effort like Dublin Core.

**Comment by jneubert** [comment]
## PLEASE VOTE THUMBS-UP/DOWN

It looks like we have reached a consensus on rejecting the ISO proposal. 

Since we are going to exclude dct:dateCopyrighted from the general comment on date formats #15 , we could however give a hint on the expected format here. Picking up a suggestion by @kcoyle in the [2018-06-27 call](https://github.com/dcmi/usage/blob/master/minutes/2018/2018-06-27.dcub-telecon-agenda.md), we should comment:
```
Typically a year.
```

**Comment by tombaker** [comment]
APPROVED:
```
Typically a year.
```
