### ISSUE TITLE
range_format.txt

### ISSUE THREAD

**Issue by kcoyle** [dcmi/usage#2]
Should not include both format and dimensions. Dimensions needs to be its own property because most resources can have both a format AND dimensions, so it's not either/or, and combining them in a single value makes for difficult parsing.

**Comment by jneubert** [comment]
[range_format.md](../blob/master/proposals/range_format.md)

**Comment by kcoyle** [comment]
Thanks, @jneubert . This sums up the issues nicely. We still need a solution, but it would be ideal to know how this is being used in current data!

**Comment by tombaker** [comment]
See issue #26 (Literal comments for dct:format)
