### ISSUE TITLE
Literal example for dct:coverage

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#23]
See [dct:coverage](../blob/master/proposals/2018_iso-related/range_coverage.md).

Literal examples for [http://purl.org/dc/terms/coverage](http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-coverage):

    EXAMPLES    1700/1799
                Boston, MA

Note: range of http://purl.org/dc/terms/coverage is http://purl.org/dc/terms/LocationPeriodOrJurisdiction.

**Comment by tombaker** [comment]
## PROPOSED comment for  http://purl.org/dc/terms/coverage:

    EXAMPLES    1700/1799
                Boston, MA

**Comment by kcoyle** [comment]
This is another one of those "A or B" fields that I just find to be unworkable. Each property should have one meaning, not two or more. And if you have both time and location? I guess you can repeat this, but I still find having more than one value "semantic" defined to be very odd.

**Comment by tombaker** [comment]
@kcoyle I agree that each property should have one meaning, not two or more.  Unfortunately, the coverage element has been part of the Dublin Core, with this sprawling definition, for over twenty years.  In 2008, the Usage Board tried to mitigate the situation by coining [`dct:spatial`](http://dublincore.org/documents/dcmi-terms/#terms-spatial) and [`dct:temporal`](http://dublincore.org/documents/dcmi-terms/#terms-temporal) as subproperties of Coverage, and it tried to give formal and explicit expression to the muddled range by coining the range class `dct:LocationPeriodOrJurisdiction`.

What is the solution? Given the definition, such as it is, I see no alternative to allowing places or dates for Coverage.  However, a usage note could also make a point along the lines of a suggestion in the [User Guide](http://wiki.dublincore.org/index.php/User_Guide/Creating_Metadata):

    If you want to make a destinction between the temporal or spatial 
    character of the content use temporal or spatial.

**Comment by jneubert** [comment]
I completely agree with @kcoyle. 

Should we take the opportunity to extend DCMI Terms with two new sub-properties (similar to dct:date):

* dct:coverageSpatial
* dct:coverageTemporal
* (other relevant uses??)

**Comment by jneubert** [comment]
Well, this crossed in the air with Toms comment, history background and (shame on me) clearing up that it's done already. 

I see Toms point that we cannot clean up the past mess, but in the wording of the comment we could perhaps be more encouraging to use the sub-properties.
```
If you can make a destinction between the temporal or spatial 
character of the content, you should use temporal or spatial.
```

**Comment by kcoyle** [comment]
+1 for note of explanation. s/destinction/distinction

**Comment by tombaker** [comment]
```
Because Coverage, for historical reasons, was so broadly defined, it is 
preferable, where possible, to use the more specific properties Temporal 
Coverage and Spatial Coverage.
```

**Comment by tombaker** [comment]
```
Because Coverage is so broadly defined, it is 
preferable to use the more specific properties (refinements), Temporal 
Coverage and Spatial Coverage.
```

**Comment by aisaac** [comment]
The case of the original suggested example has now been handled in #46
