### ISSUE TITLE
Definition of dct:relation

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#28]
See [definition_relation.md](../blob/master/proposals/2018_iso-related/definition_relation.md) - see also Issue #27 ('Properties "intended to be used with non-literal values")

DCMI Metadata Terms defines both [http://purl.org/dc/elements/1.1/relation](http://dublincore.org/documents/2012/06/14/dcmi-terms/#elements-relation) and [http://purl.org/dc/terms/relation](http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-relation) with the following definition and comment:

    A related resource.

    Recommended best practice is to identify the related resource by means of a
    string conforming to a formal identification system.

In addition, DCMI Metadata Terms notes, for [dct:relation](http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-relation) - see Issue #27 :

    This term is intended to be used with non-literal values as defined in the
    DCMI Abstract Model.  As of December 2007, the DCMI Usage Board is seeking
    a way to express this intention with a formal range declaration.

The ISO WG proposes:

    A reference to a related resource.

    Best practice is to identify the related resource by means of an URI or a
    string conforming to a formal identification system.

Note:
* In ISO 15836-2, the notes would be "NOTE x to entry:".
* Definition was originally proposed by ISO WG without initial uppercase and full stop.

**Comment by tombaker** [comment]
Closing.

**Comment by tombaker** [comment]
Reopening

**Comment by tombaker** [comment]
Reopening

**Comment by tombaker** [comment]
DCMI Metadata Terms defines both [http://purl.org/dc/elements/1.1/relation](http://dublincore.org/documents/2012/06/14/dcmi-terms/#elements-relation) and [http://purl.org/dc/terms/relation](http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-relation) with the following definition and comment:

    A related resource.

    Recommended best practice is to identify the related resource by means of a
    string conforming to a formal identification system.

The current ISO draft proposes a different definition, a slightly different comment, and a second comment:

    A reference to a related resource.

    Best practice is to identify the related resource by means of an URI or a
    string conforming to a formal identification system.

    Dublin Core Usage guide contains more information about various relations
    and how they should be encoded.

...pointing to http://www.dublincore.org/documents/usageguide/elements/.

Do we agree?

**Comment by tombaker** [comment]
I see two issues here:
* If we were to define things as "reference to", we'd need to consider re-defining, say, `dct:subject` as "A reference to the topic of the resource" (instead of "The topic of the resource).
* I do not think we should use ISO 15836 comments to point to the Dublin Core Usage Guide".

I could live with:

    Best practice is to identify the related resource by means of a URI or a
    string conforming to a formal identification system.

**Comment by tombaker** [comment]
## STRAW POLL ON COMMENT FOR `dct:relation`

The comment for `dct:relation` in DCMIMT currently says:

    Recommended best practice is to identify the related resource by means of a
    string conforming to a formal identification system.

The current ISO draft proposes a different definition:

    Best practice is to identify the related resource by means of a URI or a
    string conforming to a formal identification system.

**Comment by sarahartmann** [comment]
+1, but proposal to adapt the wording to note 2 of #30

**Comment by tombaker** [comment]
## APPROVED for 28b
```
Recommended practice is to identify the related resource by means of a URI. 
If this is not possible or feasible, a string conforming to a formal identification 
system may be provided.
```

**Comment by tombaker** [comment]
See https://github.com/dcmi/usage/blob/master/minutes/2018/2018-08-28.dcub-telecon-minutes.md for votes
