### ISSUE TITLE
Stylistic difference between DCMI Metadata Terms and ISO 15936

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#3]
[DCMI Metadata Terms](https://dublincore.org/documents/dcmi-terms/) definitions:
* start in uppercase
* may start with an article
* end with a full stop

Example

    Date (often a range) that the resource became or will become available.

[ISO 15836](https://github.com/dcmi/iso15836-2/tree/master/drafts) definitions:
* start in lowercase
* omit an initial article
* end with no punctuation

Example

    date (often a range) that the resource became or will become available

**Comment by tombaker** [comment]
PROPOSED: Accept the stylistic differences and not normalize one to the other.

**Comment by osma** [comment]
Are we supposed to use the GitHub built in emoji style +1/-1 voting (accessible from the happy face menu at the top right), or just respond +1 as text?

In any case, +1 from me.

**Comment by kaiec** [comment]
+1

**Comment by stuartasutton** [comment]
+1

**Comment by kcoyle** [comment]
Will the ISO terms use the DC/purl namespace? 

Here's my concern: there are gotchas when retrieving a string for display if you have to guess whether or not it has punctuation. This is a huge nightmare in library data. If there are situations where display strings will be retrieved from the ISO standard, that adds considerable overhead to processing of those strings for display. (Note: I get a 404 when attempting to view the ISO 15836 link, which might answer my question.)

**Comment by osma** [comment]
@kcoyle ISO isn't coining a new namespace and isn't going to publish RDF. The ISO standard can be seen as documentation for the existing DC elements/terms/resources/whatever. In my understanding, the definitions will only be used in the ISO standard PDF document.

**Comment by tombaker** [comment]
> Will the ISO terms use the DC/purl namespace? 

Yes.  They will in every respect remain DCMI terms (i.e., will not
become ISO terms).  Final approval for any changes remains with the DCMI
Usage Board.

> Here's my concern: there are gotchas when retrieving a string for
> display if you have to guess whether or not it has punctuation. This
> is a huge nightmare in library data. If there are situations where
> display strings will be retrieved from the ISO standard, that adds
> considerable overhead to processing of those strings for display.

So this is potentially an issue with the ISO document itself?

> (Note: I get a 404 when attempting to view the ISO 15836 link, which
> might answer my question.)

The iso15836-2 repo is and must remain private because we are not
allowed to post ISO drafts for public access on the Web.  I just sent
you an invite, and as soon as everyone else sends me their Github IDs, I
will issue invites so you can all view the [latest
draft](https://github.com/dcmi/iso15836-2/blob/master/drafts/ISO_CD_15836-2_2018-03-12.pdf).

**Comment by kcoyle** [comment]
So if this is just printed documentation, my concerns are allayed, and I'm:

+1

**Comment by jneubert** [comment]
+1

**Comment by aisaac** [comment]
+1

**Comment by sruehle** [comment]
+1

**Comment by jentschk** [comment]
+1

**Comment by tombaker** [comment]
DECISION We accept the stylistic difference between DCMI Metadata Terms and ISO 15836 w.r.t. punctuation, articles, and the like.

**Comment by juhahakala** [comment]
I am glad that this issue has been settled. Since ISO 15836 is being published via the normal ISO standardization process, the working group must follow ISO's editorial and other requirements.
