### ISSUE TITLE
Literal value for dct:rightsHolder

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#31]
See [note_rightsHolder](../blob/master/proposals/2018_iso-related/note_rightsHolder.md).

Add comment for [http://purl.org/dc/terms/rightsHolder](http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-rightsHolder):

    Recommended best practice is to use the name and/or URI of
    the rights holder to indicate the entity.

Range of rightsHolder is [http://purl.org/dc/terms/Agent](http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-Agent).

**Comment by aisaac** [comment]
Here's my suggestion for comment:
`Recommended best practice is to use this property with a URI for the rights holder (represented as an instance of dcterms:Agent or another equivalent or more specific class). It is acceptable, when this is not possible, to use this property with a literal (name or label) that refers to such an agent. `

I was less certain about the relevance of "or another equivalent or more specific class" but I left it in for discussion.

**Comment by tombaker** [comment]
I almost upvoted this because it seems close enough.  However:
* Not sure we need to say "represented as an instance... or more specific class".  I propose we drop this.  (I do not think in any case that the resource needs to be "represented" as an instance of dct:Agent.)
* If we drop the parenthetical text, we could simplify it to read:

    Recommended practice is to refer to the rights holder with a URI.
    If no such URI is available, it is acceptable to refer to the rights holder 
    with a literal, such as a name or label.

**Comment by kcoyle** [comment]
If you don't have an identifier, more than a name may be needed. I think we need to ask for "sufficient identifying information" - or some such. Saying the rights holder is "John Smith" or "US Government" won't really help much. So rather than naming "name or label" I'd do something like:

"Recommended practice is to allow identification of the rights holder, either with a formal identifier such as a URI or sufficient information to make identification possible."

I, too, would drop the whole "represented as an ...." as Tom says above.

**Comment by tombaker** [comment]
Today's ISO draft says:

    Note 1 to entry: Recommended best practice is to use the name and/or 
    URI of the rights holder to indicate the entity.

Following the style used for other properties, this should read:

    Note 1 to entry: Recommended practice is to refer to the rights holder
    with a name or URI.

There clearly needs to be more guidance on situations where "providing just the name of the rights holder is not enough".  However, in other issues we have rejected the notion that a literal _and_ URI be used in a single value to a given property.  Closing.

**Comment by aisaac** [comment]
I would only agree to drop "(represented as an instance of dcterms:Agent or another equivalent or more specific class)" if we add that the expected range is dcterms:Agent. Otherwise we end up with passing no expectation about what the semantic type of the resource, which I think we were interested in capturing.

NB: removing it also makes the second sentence (with "that refers to such an agent") in need of a change too.

**Comment by tombaker** [comment]
There are several proposed wordings in this thread, and I cannot with confidence make a counter-proposal.  I suggest we take the (slightly edited) text of the current ISO draft as a starting point:

    Note 1 to entry: Recommended practice is to refer to the rights holder
    with a name or URI.

Note: 
* in other issues, we have rejected the notion that a literal and a URI be used in a single value
* Juha, Karen, and Osma seem to be saying that if the value is a literal, it should not be limited to the name of the rights holder because RFC 3986 covers things like email addresses and telephone numbers.

@aisaac Would you like to make a new proposal?

**Comment by kcoyle** [comment]
Are we "referring to" or "identifying"? I think we want to identify the rights holder. Also, it could be "holder(s)"

**Comment by tombaker** [comment]
@kcoyle

> Also, it could be "holder(s)" 

dct:rightsHolder is defined as "A person or organization...".  As I see it, the comment about "the rights holder" refers to "a person organization".  I'd like to avoid implying that multiple rights holders might be named in a single value for dct:rightsHolder.

**Comment by tombaker** [comment]
## PROPOSED comment for dct:rightsHolder
```
Note 1 to entry: Recommended practice is to refer to the rights holder
with a name or URI.
```

Note that we approved, for dct:rights:

        Note 2 to entry: Recommended practice is to refer to a rights statement
        with a URI.  If this is not possible or feasible, a literal value
        (name, label, or short text) may be provided.

**Comment by tombaker** [comment]
See https://github.com/dcmi/usage/blob/master/minutes/2018/2018-08-28.dcub-telecon-minutes.md for votes

**Comment by stuartasutton** [comment]
Tom, link is broken.

**Comment by tombaker** [comment]
See https://github.com/dcmi/usage/blob/master/minutes/2018/2018-08-28.dcub-telecon-minutes.md
