### ISSUE TITLE
Add recommendation on granularity of values in ISO 15836-2 Annex B

### ISSUE THREAD

**Issue by aisaac** [dcmi/usage#35]
Cf discussion on #34 at https://github.com/dcmi/usage/issues/34#issuecomment-396543085 and following messages.

**Comment by tombaker** [comment]
## PROPOSAL

* Add a sentence to the ISO 15836-2 non-normative Annex B, page 27 (password protected) to the effect that Linked Data is expressed in statements that have one value per statement (or words to that effect).
* Delete the extra sentences in the comments to `accrualPolicy` and `accrualMethod` that say: "Where
multiple policies apply, a separate statement should be used for each policy."
