### ISSUE TITLE
Change comment for dct:subject

### ISSUE THREAD

**Issue by jneubert** [dcmi/usage#45]
Currently, the comment for dct:subject reads:

```
Typically, the subject will be represented using keywords, key 
phrases, or classification codes. Recommended best practice 
is to use a controlled vocabulary.
```

which on first sight recommends the use of literal values and is contradictionary to the note, which reads:

```
This term is intended to be used with non-literal values as defined in 
the DCMI Abstract Model (http://dublincore.org/documents/abstract-model/). 
As of December 2007, the DCMI Usage Board is seeking a way to express this 
intention with a formal range declaration.
```

When I remember correctly, we are planning to drop that latter phrase. Anyway, we should align the wording of the comment to other properties, and clearly recommend URIs over literals.

**Suggestion:**

```
Recommended practice is to refer to the subject with a URI. 
If this is not possible or feasible, a literal value that
identifies the subject may be provided, preferably from a 
controlled vocabulary.
```

**Comment by kcoyle** [comment]
I like the concept, but I think we should make clear that even the URI should be from a controlled vocabulary. Can we word it something like:

Recommended practice is to use terms from a controlled vocabulary, preferably identified with a URI. A literal value may be used if the controlled vocabulary does not use URIs.

(I'm not happy with that, but I think you get the point. I may revise it later if I get a better idea.)

**Comment by jneubert** [comment]
@kcoyle OK to the preference for controlled vocabularies. I suppose we wouldn't want to make their use mandatory. So I'd suggest a slightly different wording:
```
Recommended practice is to refer to the subject with a URI. 
If this is not possible or feasible, a literal value that
identifies the subject may be provided. Both preferably
should refer to a subject in a controlled vocabulary.
```
