### ISSUE TITLE
"Refines" or "Subproperty of"

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#47]
One commenter from the ISO WG pointed out (in comment IT018) that the term "subproperty" is not actually used in the latest draft and suggested that it therefore be deleted from Section 3.1 "Terms and definitions" (rather, the draft still says that Available "refines" Date).

Alternatively, the commenter suggests, "Refines" could be replaced throughout the document with "Subproperty of".

**Comment by stuartasutton** [comment]
I prefer "Subproperty of" because it has a relatively settled meaning, where "Refines" does not.

**Comment by tombaker** [comment]
Note of clarification:
* This is about the use of "Refines:" versus "Subproperty of" as an attribute in a term description
* This is _not_ about the use of "refines" in the wording of usage comments.
* As an attribute of term descriptions, "Refines:" _always_ means "Subproperty of"
* The issue raised (above) is that "Subproperty of" is defined in the ISO draft (3.1.10), but not used in the document.
  * However, the current ISO draft does not define "Refines:" either (!).
* "Refines:" is defined in DCMI Metadata Terms as: "A Property of which the described term is a Sub-Property."

Possible solutions discussed on telecon:
* Drop "Subproperty of" and just use "Refines"
* Drop "Refines" and replace with "Subproperty of"
  * Advantage: "Subproperty" is commonly used, while "Refines" is legacy DCMI jargon.
  * Disadvantage (?): Less applicable to XML.

Either way, since we have used "Refines:" in the past, we could leave in the definition of "Refines:" (which already says that it means "subproperty").

**Comment by kcoyle** [comment]
+1 for using "subproperty of"

I still have a question about the statement in dates that gives subproperty of more than one property, but I think we should leave it for now and let it come up again in future discussions.

**Comment by tombaker** [comment]
PROPOSAL

Replace "Refines:" with "Subproperty of" both in DCMI Metadata Terms and in ISO 15836-2.

In order to avoid potential confusion, keep the definition of "Refines:" in [DCMI Metadata Terms](http://dublincore.org/documents/dcmi-terms/#section-1):

    A Property of which the described term is a Sub-Property.

adding a note in parentheses:

     (Since 2018, DCMI documentation uses "Subproperty of:".)

Add to DCMI Metadata Terms the following definition of "Subproperty" (taken from ISO 15836-2):

    A Property that is related to
    another Property of broader scope (Superproperty), such that all resources 
    related by the Subproperty are also related by the Superproperty.

Discussion:
* The use of "refines" (for subproperty) is specific to pre-2005 Dublin Core jargon.
* We have already called the element-like entities in DCMI Metadata Terms "properties" for more than ten years (and nobody has complained).
* While not exactly inconsistent to say that one property "refines" another, saying that one is a "subproperty of" the other is clearer.

**Comment by aisaac** [comment]
I agree that "subproperty" has a more precise meaning. But this advantage has the drawback in the specific reason why the meaning is more precise. It's more precise because it's rooted in RDF semantics. The use of "subproperty" may thus be seen as discouraging use of Dublin Core terms in other contexts (XML schemas, UML models, JSON, graph data models).
A way to mitigate this would be, if we use "subproperty", would be to add a note somewhere that we don't restrict the meaning and usage of properties to RDF. And actually maybe we should do it anyway (certainly worth an issue of its own). But this may be hard to do...

**Comment by tombaker** [comment]
@aisaac I see your point but would argue that since 2000 (ambiguously) and especially since 2006-2008 (unambiguously), DCMI has presented DCMI Metadata Terms canonically as an RDF vocabulary.  This has not stopped anyone from using DC terms in other contexts, and I do not really even recall many objections to our shift from Elements to Properties. Early drafts of the DCMI Abstract Model (developed 2003-2007) introduced the terminology of Property, Class, etc, but the relationship to RDF was only clarified in later drafts. If I recall, DCMI Metadata Terms were first published with Property (instead of Element) in 2006.

I agree that we want to encourage use of DC terms in XML, UML, JSON, and graph data models, but I do not think that this should be done by retreating to vaguer, less specific data model. 

Rather, the message should be: this is an RDF vocabulary, but the terms have definitions that can be taken and used in non-RDF contexts such as XML and UML while ignoring the more RDF-specific aspects of how the vocabulary is defined.

If this message has not yet been expressed clearly enough, Annex B (p. 26) or the Introduction (p. 6) would be the places to do so in the current ISO draft.  This message could of course be reflected in the Introduction to future versions of DCMI Metadata Terms or in other DCMI documents.

[1] https://github.com/dcmi/iso15836-2/blob/master/drafts/ISO_CD_15836-2_2018-10-02.pdf

**Comment by aisaac** [comment]
The message you suggest is well in line with what I was thinking of. If such message is clearly visible in the specs, then I can live with having the RDF terminology applied across the board!

**Comment by tombaker** [comment]
PROPOSED

Replace the third paragraph on page 6 of the latest draft (see link above) with the following text:

    This set of properties and classes is expressed as an RDF vocabulary and
    may be used for Linked Data.  Each property and class is identified with a
    global identifier for use in RDF data.  Creators of non-RDF metadata can
    use the vocabulary in non-RDF contexts, such as XML and UML, by
    disregarding both the global identifier and the formal implications of the
    RDF-specific aspects of term definitions.  Such users can take domain,
    range, subproperty, and subclass relations as usage suggestions and focus
    on the natural-language text of definitions, usage notes, and examples.

**Comment by kcoyle** [comment]
Excellent wording, Tom. I just wonder about using UML as an example since it is a modeling language not a schema. Could we use JSON or some other common schema language? (I can't think of others, asking for suggestions here.)

**Comment by tombaker** [comment]
@kcoyle I was wondering the same re: UML and thinking that "relational databases" (which are often _designed with_ UML) might be clearer.

**Comment by osma** [comment]
I want JSON mentioned alongside XML so we don't look like dinosaurs ;) Otherwise agree with everything

**Comment by tombaker** [comment]
Resolved - see above
