### ISSUE TITLE
"Element" and "Property"

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#48]
Section 3.1 "Terms and definitions" currently says that "property" is a synonym of "element".  One ISO commenter suggests that "element" therefore also be defined in Section 3.1 (comment IT026).

How would we want to define "element", and is it really a _synonym_ for "property", or are the two terms simply being used interchangeably?

Should we perhaps acknowledge, in their definitions, that "element" was historically somewhat more ambiguous than "property", which specifically reflects its meaning in RDF?

**Comment by osma** [comment]
Can a class also be an element? In DC context, I think both "element" and "term" have been used with a somewhat ambiguous meaning...

**Comment by jneubert** [comment]
+1 to Stuart. This goes fine with "Subproperty of" :)

I've searched for "element" in http://dublincore.org/documents/dcmi-terms/, and found one use in a comment for dct:type - where it should be replaced by "property".

I cannot vote on Stuarts (1) or (2), because I don't know how much "element" was used in the past.

**Comment by tombaker** [comment]
PROPOSAL (based on Stuart's)

Use "property" throughout, without mention of "element".  As Joachim points out, this would involve correcting a comment for dct:type.

Add to Section 3.1. an entry for "element" defined as:

    A specific aspect, characteristic, attribute, or relation used to
    describe resources. Since December 2006, an "element" has been 
    referred to in DCMI document as a "property", though the use of 
    "element" persists in ISO 15836-1, "The Dublin Core metadata element
    set" and is implied by DCMI persistent identifiers that start with 
    http://purl.org/dc/elements/1.1/.

**Comment by aisaac** [comment]
Same comment - and uneasiness - on my side as at https://github.com/dcmi/usage/issues/47#issuecomment-431054186

**Comment by tombaker** [comment]
@aisaac Same response on my side as in https://github.com/dcmi/usage/issues/47#issuecomment-431277963

**Comment by tombaker** [comment]
Resolution of this issue depends on, and is included in the resolution of, Issue #47.  This issue can therefore be closed as a separate issue.
