### ISSUE TITLE
Use of examples ("such as") in definitions - dct:creator

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#49]
On August 27, we unanimously approved the following definition for dct:creator:

        An entity, such as a person, organization, or service, responsible for
        creating the resource.

One ISO WG commenter (comment IT036) feels that it is never a good practice to add the phrase "such as..." in a definition.  One might also handle this with examples as has been done in other cases, like Contributor (which says: "EXAMPLES: a person, an organization, or a service").

The commenter also points out that this property refines Contributor, where it is clearly stated (in the Examples) that Contributors may be persons, organizations, or services and feels that re-stating the same thing would amount to useless repetition.

In the latest ISO draft, the words "such as a person, organization, or service" have been dropped and the word "primarily" has been re-introduced:

    entity primarily responsible for making the resource

I suggest we clarify the definition and take a position on:
* re-introduction of "primarily"
* whether examples ("such as") belong in a definition

**Comment by tombaker** [comment]
DECISION

* Remove "primarily".

**Comment by osma** [comment]
The example "Verohallinto. Suomi" is incorrect. (It means "Tax administration. Finland")
If we want to keep it, the order should be switched: "Suomi. Verohallinto"

**Comment by kcoyle** [comment]
Examples all should follow the example format under date, and all do except for organization and creator:

The format is:

EXAMPLE 1	2018
EXAMPLE 2	2016-03-04
etc.

Change examples under **contributor** from:

EXAMPLES: a person, an organization, or a service

to

EXAMPLE 1 	Shakespeare, William (a person)
EXAMPLE 2	http://www.isni.org/isni/0000000121032683 (IRI for a person)
EXAMPLE 3	Hubble telescope (a data service)
EXAMPLE 4	Suomi. Verohallinto (an organization)


change examples under **creator** from:

EXAMPLES: 	Shakespeare, William
			http://isni.org/isni/0000000121032683
			Hubble telescope
			Suomi. Verohallinto
			
to

EXAMPLE 1 	Shakespeare, William (a person)
EXAMPLE 2	http://www.isni.org/isni/0000000121032683 (IRI for a person)
EXAMPLE 3	Hubble telescope (a data service)
EXAMPLE 4	Suomi. Verohallinto (an organization)

_Note that this means that there is no long a limited list ("person, organization, or service") under creator and collaborator, but this may not be a bad thing. They now read: **entity responsible for ...** and this means that any kind of entity is included._

**Comment by osma** [comment]
I upvoted @kcoyle's suggestion above, which is great. 

However, I feel a bit nervous about Example 4 "Suomi. Verohallinto" under both **creator** and **contributor**. As much as I love the tax authorities of my country, I think it's a bit disingenious to use the tax administration of a small country as the only example of an organization in an international standard. Even the name of that organization is in a language that 99.99% of the world population cannot understand. I think a more recognizable example - like Examples 1-3 are - would be better here.

I suggest changing

    EXAMPLE 4 Suomi. Verohallinto (an organization)

to 

    EXAMPLE 4 UNESCO (an organization)

under both **creator** and **contributor**. UNESCO is a far better known, international organization. There is also data like this in the wild - the [UNESCO Thesaurus](http://vocabularies.unesco.org/browser/thesaurus/en/) in RDF contains these triples:

```
<http://vocabularies.unesco.org/thesaurus> a skos:ConceptScheme ;
	dc:contributor "UNESCO" ;
	dc:creator "UNESCO" .
```

**Comment by kcoyle** [comment]
That's very modest of you, Osma, but I admit that I must agree that a more internationally-known organization would be best. I'm fine with UNESCO.

**Comment by tombaker** [comment]
Resolved - see https://github.com/dcmi/usage/issues/49#issuecomment-430313969
