### ISSUE TITLE
dct:conformsTo

### ISSUE THREAD

**Issue by kcoyle** [dcmi/usage#5]
This is currently defined as an object property with a range of dct:Standard. I'm not convinced that all standards have true IRI identifiers, nor that "conforms to" needs to be to a formal standard. The W3C DXWG group may wish to use this term as an annotation standard.

**Comment by stuartasutton** [comment]
Karen, some background, the `conformsTo` property was originally proposed as domain-specific in 2001 by the dc:education community to  provide a means for referencing standards defining competencies--e.g., a competency in the Common Core State standards for K12 math etc. Through Usage Board discussions leading to recommended status (also in 2001), the scope/definition of the property was generalized. I don't recall the discussion in 2008 on the change in range (http://dublincore.org/documents/2008/01/14/domain-range/).

**Comment by kcoyle** [comment]
It occurs to me that "conformsTo" would be better if we drop the subclass to dct:Standard, so conformsTo could be anything, and it doesn't have to have the Standard baggage. But that would leave us with no property linked to dct:Standard, I believe. Just an idea.

**Comment by tombaker** [comment]
Closing this issue for now.  It is related to the discussion about dct:Standard, about which we may to have a proposal from the ISO WG.  Assuming we have such a proposal, I will make sure to link to this closed issue.
