### ISSUE TITLE
Wording of usage comments for Date and its subproperties

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#51]
One ISO WG commenter takes issue with the usage comment for Date (comment IT037) and its sub-properties (comments IT041, IT043, IT047, IT050), which currently says:

    Recommended practice is to express the date, time, or period according...

* Date is defined as a point or period of time, hence it is wrong to write "date, time, or period".  
* The commenter recommends: "Recommended practice is to express the date according...".

The ISO secretariat responded: Although we do not agree that it is wrong to write "date, time and period" since all these are covered by ISO 8601, we agree that it is not necessary to repeat this information in the note.  Accordingly, the draft has been revised to drop "time or period":

    Recommended practice is to express the date...

Do we agree?

**Comment by tombaker** [comment]
PROPOSAL

    The Usage Board agrees to changing "date, time or period" 
    (in the usage comment) to just "date".

Discussion: The usage note points to three date (or date/time) specifications, which implies that anything formatted according to one of the three would be appropriate as a value for Date, and we already include times and date ranges in the examples.  This seems like enough in light of the space limitations of a usage note.

**Comment by aisaac** [comment]
I think the repetition is a cheap price to pay for clarity on what may be included. How many users are we going to deeply puzzle by removing an explicit list in order to please a handful of experts on date/time and standard writers? And would the repetition make the life of these experts so awful?

**Comment by tombaker** [comment]
I try to avoid words with slashes ("date/time"), but in this case, the comment to Date already cites an ISO Extended Date/Time Format, so I would agree to using "date/time" here.  New proposal follows...

**Comment by tombaker** [comment]
PROPOSAL

The Usage Board agrees to changing "date, time or period"  (in the usage comment) to "date or date/time":

    Recommended practice is to express the date or date/time according to...

**Comment by jneubert** [comment]
What harm would it do to mention "period" too - 

    ... express the date, date/time or period according to ...

**Comment by tombaker** [comment]
Noting that Date is _defined_ as a "point or period of time", I see two options:
* Leave it as just "date" -- the option favored by the ISO commenter and Juha, who agree that it is not necessary to repeat this information in the note. I could live with this.
* Repeat the full information as proposed by Joachim, but then use the phrase from the definition, "period of time":

    ... express the date, date/time, or period of time according to ...

**Comment by tombaker** [comment]
As an aside, note that ISO 15836-2 also defines a class, PeriodOfTime, defined as:

      period of time that is _named or_ defined by its start or end dates

which is used as a range for Temporal Coverage.

In our most recent call, I believe we affirmed that Date was _not_ intended to be used with named periods. As defined, however, this _would_ be acceptable for Coverage.

I see a slight potential for confusion here, though nothing that could not be addressed with examples, especially on the per-property "term pages" we plan to generate on the new website.

**Comment by tombaker** [comment]
PROPOSED

    Recommended practice is to express the date, date/time, or period of time according to ...

**Comment by tombaker** [comment]
Resolved
