### ISSUE TITLE
Range classes representing unions (with `Or` in their names)

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#58]
The document [Domains and Ranges for DCMI Properties](http://dublincore.org/documents/domain-range/) of 2008 presents the following classes: <img src=http://dublincore.org/documents/2008/01/14/domain-range/classes.jpg>

Note that two classes were created to represent the union of range classes:
* `LocationPeriodOrJurisdiction`
* `MediaTypeOrExtent`

The Usage Board recognized that these "lumpy" classes were inelegant but felt that they accurately reflected the semantics of established definitions that were themselves lumpy.

With `rangeIncludes`, however, it is unclear whether we will still need these "union" classes at all, and I strongly suspect that these classes can serve no useful purpose other than as formal RDFS ranges for properties with uniquely lumpy definitions.  If so, might we consider deprecating them?  Put another way, how would we justify including them in an ISO standard if they are no longer being used for their one useful purpose?

**Comment by osma** [comment]
Agree that we should deprecate these and probably also omit them from the ISO standard.

**Comment by aisaac** [comment]
Assuming that we still could end up with traditional RDFS ranges next to the new rangeIncludes (but is it the case?) I would suggest a more complex approach to make sure that we don't lose information.
1. If it appears that the a 'lumpy' class would be used in a rangeIncludes, i.e. the property can be used with other types of objects, then we the do not add a rangeIncludes for the lumpy class and instead add rangeIncludes to the 'component' sub-classes.
2. If at the end of checking this for all properties a 'lumpy' class is not used anymore, we deprecate this.

Of course I would cross my fingers that this allows us to deprecate all the 'lumpy' classes while ensuring my peace of mind that we've not removed a 'real/valid RDFS range axiom' by being too hasty.

**Comment by osma** [comment]
Why would we have traditional RDFS ranges next to rangeIncludes? I think we were planning to retain them only in the rdfs:Literal case. All others would be converted to rangeIncludes.

**Comment by aisaac** [comment]
Have we decided that we would remove all RDFS ranges? And what if some of these RDFS ranges were actually correct?
Again I'm rather in favor of removing them as much as possible, but if some could help, why not keep them in?
I guess what I'm asking (as I've done in some other range-related ticket) is to examine the situation and decide case-by-case.

**Comment by osma** [comment]
@aisaac No, we have not made that decision formally, but it was proposed in the opening post of #43 which describes what @tombaker felt represented the consensus in July:

> Substitute dcam:rangeIncludes for rdfs:range (and dcam:domainIncludes for rdfs:domain) for all properties except for properties with a range of rdfs:Literal (which will continued to use rdfs:range).

I think we have to postpone the decision here until #43 is decided. I agree that if we are going to decide on replacing RDFS ranges on a case-by-case basis, then the cautious approach proposed by @aisaac makes sense (and of course, the rangeIncludes declarations should target the component sub-classes, not the lumps). 

OTOH, the existence of these lumpy classes is, in my view, one of the main arguments for switching to rangeIncludes so I would be rather surprised (and disappointed) if we didn't switch into rangeIncludes for at least these cases.

**Comment by aisaac** [comment]
@osma  I was the one dissenting on @tombaker's proposal and I still stand behind my comment at https://github.com/dcmi/usage/issues/43#issuecomment-407781058
But yes I agree with you, I too hope we can get rid of them...

**Comment by tombaker** [comment]
The worst of the lumpy classes are:
* `LocationPeriodOrJurisdiction`: used _only_ with Coverage
* `MediaTypeOrExtent`: used _only_ with Format

**Comment by tombaker** [comment]
PROPOSED

* "Deprecate" (but not delete): LocationPeriodOrJurisdiction and MediaTypeOrExtent
* Omit these from the ISO standard
* Assign their subclasses separate with rangeIncludes
* Remove subclass relations

**Comment by aisaac** [comment]
Concretely, replace the axioms
- coverage range LocationPeriodOrJurisdiction by
-- coverage rangeIncludes Location
-- coverage rangeIncludes Period
-- coverage rangeIncludes Jurisdiction
- format range MediaTypeOrExtent by
-- format rangeIncludes MediaType
-- format rangeIncludes Extent

**Comment by tombaker** [comment]
Resolved
