### ISSUE TITLE
URI dereferencing broken

### ISSUE THREAD

**Issue by pietercolpaert** [dcmi/usage#66]
When dereferencing the dcterms URIs with base URI http://purl.org/dc/terms/, an apache directory listing is given instead of the overview of terms

**Comment by tombaker** [comment]
@pietercolpaert Thank you very much for bringing this to our attention!  We heard about this simultaneously from several people.  This was due to incorrect configuration on our end, and we have fixed it.

**Comment by pietercolpaert** [comment]
Thank you very much!
