### ISSUE TITLE
Definition of "audience"

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#70]
The definition of "audience" currently reads:

> class of entity for whom the resource is intended or useful

One reviewer writes:
> What is an "entity"? Not defined in the definition section.  Why not use "class of agents"?

This is a comment that we _must_ address.

**Comment by stuartasutton** [comment]
I can support "Class of agents for whom the resource is intended or useful"

**Comment by tombaker** [comment]
STRAWMAN PROPOSAL

Change the definition of "audience", which currently reads:

> class of entity for whom the resource is intended or useful

to read:

> class of agents for whom the resource is intended or useful

DISCUSSION
* Back in 2002, we were not thinking of machine learning - we were thinking of people ("agents").

**Comment by tombaker** [comment]
DECISION (see above)
