### ISSUE TITLE
Designating inverse properties

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#74]
One reviewer points out that `dct:isFormatOf` is an inverse property of `dct:hasFormat` and wonders why the document does not point this out.

**Comment by tombaker** [comment]
The reviewer makes a good point.  For discussion.

**Comment by stuartasutton** [comment]
There are others:
>hasPart/isPartOf
hasVersion/isVersionOf

Does that mean declaring them formally as inverse at the schema level (owl:inverseOf/schema:inverseOf)? Or just point it out a comment.

**Comment by kcoyle** [comment]
I don't find "inverseOf" in the RDF/RDFs documentation. It only shows up in OWL. Unless I've missed something, I would say that DCMI Terms are defined in RDF/RDFs, not OWL, so at best inverse is conceptual, but cannot be inferred formally. Thus, I think that the names of the terms suffice to explain this.

**Comment by tombaker** [comment]
@kcoyle @stuartasutton The reviewer does not suggest that they be _formally_ defined as inverse, so a comment would suffice.

**Comment by kcoyle** [comment]
So a comment on each saying "The inverse of X". That works for me.

**Comment by tombaker** [comment]
STRAWMAN PROPOSAL

For each pair of inverse properties, add a note pointing from one to the other as per the following template:

    Note 1 to entry: This property is the inverse of the property @@@.

Example, for `dct:hasFormat`:

    Note 1 to entry: This property is the inverse of the property is format of.

DISCUSSION
* Writing `of the property is format of` looks odd without punctuation, but Note 2 for coverage reads `use the more specific subproperties temporal coverage and spatial coverage`, possibly because of ISO punctuation rules.  It would look clearer to me if written in uppercase, `of the property Is format of` or `of the property Is Format Of`, or with punctuation, `of the property "is format of"`.  However, such a change could trigger many others in the document, for the sake of consistency.

**Comment by tombaker** [comment]
This note would need to be added to the ten properties of the six following pairs:

* `isFormatOf`/`hasFormat`
* `isPartOf`/`hasPart`
* `isRequiredBy`/`requires`
* `isVersionOf`/`hasVersion`
* `isReferencedBy`/`references`
* `isReplacedBy`/`replaces`

**Comment by juhahakala** [comment]
There are at least three ways of dealing with this. Adding twelve notes is one and perhaps the most obvious one of them. But is is also possible to list the 12 properties above in the end of clause 3.2, and say that the following properties have inverse relationship. Or this information could be placed in the user manual. IMO the first option (adding the 12 notes) may be the best one, since then the information is impossible to miss. If it is placed in the end of clause 3.2 or only in the user manual, the users of ISO Online Browsing Platform will not see it.

**Comment by tombaker** [comment]
## PROPOSED - please vote

Add a note to each of the twelve properties in the following pairs:

* `isFormatOf`/`hasFormat`
* `isPartOf`/`hasPart`
* `isRequiredBy`/`requires`
* `isVersionOf`/`hasVersion`
* `isReferencedBy`/`references`
* `isReplacedBy`/`replaces`

For example, the note for `isFormatOf` (3.2.28) would read:

    NOTE # to entry: This property is an inverse property of hasFormat (3.2.23).

**Comment by kcoyle** [comment]
But for the future, can we at least agree that creating two properties to have an "inverse of" is not necessary? If X references Y, then Y is referenced by X. The problem with having explicit inverses is if someone states: X references Y, Y is referenced by Z, Z is referenced by X. That may be true, but it's a mess and it seems to beg for errors to be made.

**Comment by staplegun** [comment]
I think it depends whether DCT terms have a life outside of the RDF world? 

If there is an inference engine then yes the inverse can be inferred, but in a record-based world the metadata record creator may not have access to the other record to add the property. For example, I may want to say this resource `isVersionOf` another resource, but if we only have `hasVersion` I may not be able to add that property to the other metadata record.

**Comment by aisaac** [comment]
+1 to @staplegun 's remark. In the Europeana Data Model we've used some properties that are "in the wrong direction" so to say, and it does not make it easy for "traditional" (i.e. not aware of linked data subtleties) consumers to get these fields, while we still want them to use our APIs.

**Comment by aisaac** [comment]
To @kcoyle 's point about the inverse not being in RDF(S) but in OWL, she's right, stating an inverse relationship requires OWL. But we could represent it in RDFS using a dual sub-property statement: X rdfs:subPropertyOf Y and Y rdfs:subPropertyOf X. It's a bit awkward but does the job from the perspective of inference engines.

**Comment by tombaker** [comment]
@aisaac It was always my understanding that `X rdfs:subPropertyOf Y` and `Y rdfs:subPropertyOf X` would be functionally equivalent to `owl:equivalentProperty`, not an inverse relationship.  Could someone please test this with an inference engine?

**Comment by tombaker** [comment]
+1 to @staplegun and @aisaac though I'm not sure what the implications are for DCMI Metadata Terms.  If stating the relationship formally is only helpful in the RDF world, is there anything more we can do than say in prose that the two properties are inverse?

**Comment by tombaker** [comment]
Stuart points out that Schema.org has https://schema.org/inverseOf .

**Comment by aisaac** [comment]
I'm fine saying it in prose only and postponing the formal representation

**Comment by tombaker** [comment]
ACTION Tom to create an issue about whether to state this formally.  (For what use cases would we actually need this?)

**Comment by tombaker** [comment]
DECISION (see above).

Created issue #76 ("Do we need to state inverse property relations formally?") for future discussion.
