### ISSUE TITLE
Definition of dct:available

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#8]
**2017-07-03: PLEASE VOTE [BELOW](https://github.com/dcmi/usage/issues/8#issuecomment-402155229)**

Final decision will be recorded at [definition_available.md](../blob/master/proposals/2018_iso-related/definition_available.md)

-------
PROPOSED

Change definition of [http://purl.org/dc/terms/available](http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-available):

    Date (often a range) that the resource became or will become available.

to read:

    Date the resource became available, or an estimate (often a range) of when
    it will become available.

Rationale

* Proposed by ISO WG
* Clarifies that the date something _became_ available is a single date (and not a range)
* Clarifies that the date something _will become_ available may be an estimate and is often a range

**Comment by kcoyle** [comment]
I don't think I've ever seen a range as an estimate of availability. In fact, for books it is a specific date. Where did this range info come from?

**Comment by kcoyle** [comment]
But we don't have to accept ISO's definition, right? An estimate \= range. I would be happy to know why they chose that, but it doesn't not read as correct to me.

**Comment by kcoyle** [comment]
"Fixed or estimated date upon which the resource is expected to be available."

I don't think this excludes ranges, but I still don't think that ranges are usage, unless someone can demonstrate otherwise. I still would like to know what the ISO group was working with, if we can have that information.

**Comment by jtennis** [comment]
Does range imply the resource will not be available at a certain point?

**Comment by kcoyle** [comment]
@jtennis I never heard of it used that way. But I take your point - it may be that this is available from June - August, 2018. However, the "became or will become" doesn't seem to match the "date or dates of availability" such as what one would use for the performance dates of a play or a museum exhibit. If that is what is meant then I think it needs a different definition. (BTW, this is an area in which schema.org excels - dates and times for events, opening hours for shops, etc.)

**Comment by kcoyle** [comment]
@tombaker  - No, I still find it to be confusing. If something is (became) available, it has a publication date, no? If not, then does this not apply to things that will be published? What's "available" if not publication? And the range issue comes directly from the DCterms, which I didn't realize before now, but that's my mis-reading and I apologize. If we stick with the DCterms definition, then I have no problem with the ISO wording, which is clearer but doesn't solve the underlying problem.

**Comment by tombaker** [comment]
@kcoyle So might we simply resume the vote on the ISO wording (above)?  I'm sure this is not the only definition which, on closer inspection, raises problems.  I'd like to set up a structure where we could capture usage-related issues such as these for inclusion in per-term documentation pages and maintenance by crowd-sourcing (which I guess means pull requests) - so please hold that thought!

**Comment by tombaker** [comment]
PROPOSED

Change definition of [http://purl.org/dc/terms/available](http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-available):

    Date (often a range) that the resource became or will become available.

to read:

    Date (sometimes a range) that the resource became or will become available.

Rationale

* On the [June 27 telecon](https://github.com/dcmi/usage/blob/master/minutes/2018/2018-06-27.dcub-telecon-minutes.md) it was decided that available evidence does not support the statement that the date is "often" a range.

**Comment by kcoyle** [comment]
I'm for skipping mentioning ranges at all because of the use of "became/become". If it were the total time in was in publication then a range would make sense for serial items, but becoming is a singular moment in my vocabulary.

**Comment by tombaker** [comment]
Changing "(often a range)" to "(sometimes a range)" is the least disruptive thing we can do here.  @kcoyle point taken, though this has not come up as an issue until now.  I suggest we turn our attention next to usage guidance then, if need be, we can re-open this issue.

**Comment by aisaac** [comment]
I'm re-opening as I think the number of votes on the last proposal is lower than what we've got for the other issues.

**Comment by tombaker** [comment]
It has been suggested that if this definition says "sometimes a range", then the definition for [dct:available](http://dublincore.org/documents/dcmi-terms/#terms-available), which currently reads:

    Date (often a range) that the resource became or will become available.

should also read:

    Date (sometimes a range) that the resource became or will become available.

**Comment by tombaker** [comment]
## APPROVED

Definition of dct:available reads:
```
Date (sometimes a range) that the resource became or will become available.
```
