### ISSUE TITLE
Drop reference to W3C Note on Date and Time Formats in `dct:date` comment?

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#81]
The comment for Date reads:

    Date may be used to express temporal information at any level of
    granularity.  Recommended practice is to express the date, date/time, or
    period of time according to ISO 8601-1 or a published profile of the ISO
    standard, such as the W3C Note on Date and Time Formats or the
    Extended Date/Time Format Specification.

Juha points out that the W3C Note is not really a published profile of ISO
8601-1:2019. It did apply to ISO 8601:1988, in which it was still possible to
specify year with two digits (and W3C Note forbids that). 

Since all the versions of ISO 8601 since year 2000 only approve year in full
format (YYYY), referring to the W3C Note in the context of ISO 8601-1:2019
arguably provides zero added value.

Juha suggests dropping the reference.

See: https://www.w3.org/TR/NOTE-datetime (1997)

**Comment by staplegun** [comment]
I like the W3C Note as it is easy to read and use, unlike the EDTF spec, but we didn't have EDTF back then and we do now and ISO8601 has moved on, so it makes sense to refer to examples that apply in the current context, to reduce potential confusion.

**Comment by tombaker** [comment]
@staplegun Are you then agreeing with the proposal to drop mention of the W3C note?

@all: This does not need to be decided right now.  We are very close to publishing a new release of DCMI Metadata Terms.  In the interest of having that release align as closely as possible with the ISO release, we will keep the reference to the W3C Note for now.

**Comment by staplegun** [comment]
@tombaker I'm not disagreeing :) I'm undecided which of the W3C note and EDTF gives more help or does more harm.
